//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgeons
    {
        public int pk { get; set; }
        public int id { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public Nullable<int> fileId { get; set; }
    
        public virtual File File { get; set; }
    }
}
