//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgeries
    {
        public int pk { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> exitDate { get; set; }
        public Nullable<int> plannedDuration { get; set; }
        public string status { get; set; }
        public Nullable<int> surgeonId { get; set; }
        public Nullable<int> fileId { get; set; }
    
        public virtual File File { get; set; }
    }
}
